# Generated by Django 4.0.3 on 2022-03-11 22:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crm_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='moviemovierecommodel',
            table='movie_to_movie',
        ),
    ]
