# Generated by Django 4.0.3 on 2022-03-04 04:49

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm_app', '0002_usergenremodel_tvratingmodel_standardunitsmodel_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='BookModel',
            fields=[
                ('id', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('date_published', models.CharField(max_length=15)),
                ('publisher', models.CharField(max_length=50)),
                ('description', models.TextField()),
                ('link', models.CharField(max_length=100)),
                ('cover_link', models.CharField(max_length=100)),
                ('amazon_link', models.CharField(max_length=100)),
                ('content_rating', models.CharField(max_length=5)),
                ('isbn_id', models.CharField(max_length=15)),
            ],
            options={
                'db_table': 'books',
            },
        ),
        migrations.CreateModel(
            name='BookRecpModel',
            fields=[
                ('id', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=200)),
                ('series', models.CharField(max_length=200)),
                ('author', models.CharField(max_length=100)),
                ('genre', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=20), size=None)),
            ],
            options={
                'db_table': 'books_recp',
            },
        ),
        migrations.CreateModel(
            name='CastModel',
            fields=[
                ('id', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=30)),
                ('profile_path', models.CharField(max_length=50)),
                ('popularity', models.CharField(max_length=5)),
            ],
            options={
                'db_table': 'cast_members',
            },
        ),
        migrations.CreateModel(
            name='GameModel',
            fields=[
                ('id', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('available_at', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=15), size=None)),
                ('release', models.CharField(max_length=10)),
                ('background_image', models.CharField(max_length=100)),
                ('website', models.CharField(max_length=100)),
                ('screenshots', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=100), size=None)),
                ('platforms', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=10), size=None)),
            ],
            options={
                'db_table': 'games',
            },
        ),
        migrations.CreateModel(
            name='GameRecpModel',
            fields=[
                ('id', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('tags', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=20), size=None)),
                ('publishers', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=20), size=None)),
                ('genres', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=20), size=None)),
                ('esrb_rating', models.CharField(max_length=20)),
            ],
            options={
                'db_table': 'games_recp',
            },
        ),
        migrations.CreateModel(
            name='MovieModel',
            fields=[
                ('id', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('adult', models.BooleanField(default=False)),
                ('imdb_id', models.CharField(max_length=20)),
                ('language', models.CharField(max_length=5)),
                ('popularity', models.CharField(max_length=5)),
                ('poster_path', models.CharField(max_length=30)),
                ('release_date', models.CharField(max_length=15)),
                ('runtime', models.CharField(max_length=5)),
                ('spoken_languages', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=5), size=None)),
                ('status', models.CharField(max_length=10)),
                ('tagline', models.TextField()),
                ('backdrop_path', models.CharField(max_length=30)),
            ],
            options={
                'db_table': 'movies',
            },
        ),
        migrations.CreateModel(
            name='MovieRecpModel',
            fields=[
                ('id', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=100)),
                ('overview', models.TextField()),
                ('genre', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=20), size=None)),
                ('production_companies', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=20), size=None)),
                ('cast', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=20), size=None)),
                ('keywords', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=30), size=None)),
            ],
            options={
                'db_table': 'movies_recp',
            },
        ),
        migrations.CreateModel(
            name='TvModel',
            fields=[
                ('id', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('in_production', models.BooleanField(default=False)),
                ('last_air_date', models.CharField(max_length=15)),
                ('no_episodes', models.IntegerField()),
                ('no_seasons', models.IntegerField()),
                ('original_languages', models.CharField(max_length=5)),
                ('poster_path', models.CharField(max_length=30)),
                ('spoken_languages', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=5), size=None)),
                ('status', models.CharField(max_length=10)),
                ('tagline', models.TextField()),
            ],
            options={
                'db_table': 'tv',
            },
        ),
        migrations.CreateModel(
            name='TvRecpModel',
            fields=[
                ('id', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=100)),
                ('overview', models.TextField()),
                ('genres', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=20), size=None)),
                ('prodcution_companies', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=20), size=None)),
                ('keywords', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=20), size=None)),
                ('type', models.CharField(max_length=10)),
                ('cast', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=20), size=None)),
            ],
            options={
                'db_table': 'tv_recp',
            },
        ),
    ]
