# Generated by Django 4.0.3 on 2022-03-06 02:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crm_app', '0003_bookmodel_bookrecpmodel_castmodel_gamemodel_and_more'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='usermodel',
            managers=[
            ],
        ),
        migrations.RenameField(
            model_name='bookrecpmodel',
            old_name='genre',
            new_name='genres',
        ),
        migrations.RenameField(
            model_name='movierecpmodel',
            old_name='cast',
            new_name='cast_member',
        ),
        migrations.RenameField(
            model_name='movierecpmodel',
            old_name='genre',
            new_name='genres',
        ),
        migrations.RenameField(
            model_name='tvmodel',
            old_name='original_languages',
            new_name='original_language',
        ),
        migrations.RenameField(
            model_name='tvrecpmodel',
            old_name='prodcution_companies',
            new_name='production_companies',
        ),
    ]
