# Generated by Django 4.0.3 on 2022-03-06 02:21

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm_app', '0004_alter_usermodel_managers_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='moviemodel',
            name='cast_member',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=20), null=True, size=None),
        ),
        migrations.AddField(
            model_name='moviemodel',
            name='genres',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=20), null=True, size=None),
        ),
        migrations.AddField(
            model_name='moviemodel',
            name='keywords',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=30), null=True, size=None),
        ),
        migrations.AddField(
            model_name='moviemodel',
            name='overview',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='moviemodel',
            name='production_companies',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=20), null=True, size=None),
        ),
        migrations.AddField(
            model_name='moviemodel',
            name='title',
            field=models.CharField(default='', max_length=100),
        ),
    ]
