# Generated by Django 4.0.3 on 2022-03-15 07:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm_app', '0004_brokenlinkmodel_created_date_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='inaccuraterecommodel',
            name='user',
        ),
        migrations.AddField(
            model_name='inaccuraterecommodel',
            name='count',
            field=models.IntegerField(default=1),
        ),
    ]
