# Generated by Django 4.0.3 on 2022-03-06 02:24

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm_app', '0005_moviemodel_cast_member_moviemodel_genres_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tvmodel',
            name='cast',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=20), null=True, size=None),
        ),
        migrations.AddField(
            model_name='tvmodel',
            name='genres',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=20), null=True, size=None),
        ),
        migrations.AddField(
            model_name='tvmodel',
            name='keywords',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=20), null=True, size=None),
        ),
        migrations.AddField(
            model_name='tvmodel',
            name='overview',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='tvmodel',
            name='production_companies',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=20), null=True, size=None),
        ),
        migrations.AddField(
            model_name='tvmodel',
            name='title',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='tvmodel',
            name='type',
            field=models.CharField(max_length=10, null=True),
        ),
    ]
