# Generated by Django 4.0.3 on 2022-03-15 07:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm_app', '0005_remove_inaccuraterecommodel_user_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='inaccuraterecommodel',
            name='recommended_type',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='inaccuraterecommodel',
            name='type',
            field=models.IntegerField(default=0),
        ),
    ]
