# Generated by Django 4.0.3 on 2022-03-08 05:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('crm_app', '0006_tvmodel_cast_tvmodel_genres_tvmodel_keywords_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='GenreModel',
            fields=[
                ('id', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=20)),
            ],
            options={
                'db_table': 'genres',
            },
        ),
        migrations.CreateModel(
            name='KeywordModel',
            fields=[
                ('id', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=20)),
            ],
            options={
                'db_table': 'keywords',
            },
        ),
        migrations.CreateModel(
            name='TvGenreModel',
            fields=[
                ('id', models.CharField(max_length=101, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=20)),
            ],
            options={
                'db_table': 'genres_tv',
            },
        ),
        migrations.RenameField(
            model_name='bookmodel',
            old_name='description',
            new_name='overview',
        ),
        migrations.RenameField(
            model_name='moviemodel',
            old_name='cast_member',
            new_name='cast_members',
        ),
        migrations.RenameField(
            model_name='movierecpmodel',
            old_name='cast_member',
            new_name='cast_members',
        ),
        migrations.RenameField(
            model_name='tvmodel',
            old_name='cast',
            new_name='cast_members',
        ),
        migrations.RenameField(
            model_name='tvrecpmodel',
            old_name='cast',
            new_name='cast_members',
        ),
        migrations.CreateModel(
            name='MovieTvRecomModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.DecimalField(decimal_places=2, default=0, max_digits=7)),
                ('movie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='crm_app.moviemodel')),
                ('tv', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='crm_app.tvmodel')),
            ],
        ),
        migrations.CreateModel(
            name='MovieMovieRecomModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.DecimalField(decimal_places=2, default=0, max_digits=7)),
                ('movie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subject_movie', to='crm_app.moviemodel')),
                ('movie2', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recom_movie', to='crm_app.moviemodel')),
            ],
        ),
    ]
