# Generated by Django 4.0.3 on 2022-03-15 16:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm_app', '0007_remove_brokenlinkmodel_user_brokenlinkmodel_count_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='brokenlinkmodel',
            name='name',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='inaccuratedatamodel',
            name='name',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='inaccuraterecommodel',
            name='name',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='inaccuraterecommodel',
            name='recommended_name',
            field=models.CharField(default='', max_length=100),
        ),
    ]
