# Generated by Django 4.0.3 on 2022-03-17 01:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crm_app', '0008_brokenlinkmodel_name_inaccuratedatamodel_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='inaccuratedatamodel',
            name='name',
        ),
    ]
