# Generated by Django 4.0.3 on 2022-03-08 05:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crm_app', '0008_alter_moviemovierecommodel_table_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='moviemovierecommodel',
            old_name='movie',
            new_name='movie_id1',
        ),
        migrations.RenameField(
            model_name='moviemovierecommodel',
            old_name='movie2',
            new_name='movie_id2',
        ),
    ]
