# Generated by Django 4.0.3 on 2022-03-17 01:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crm_app', '0009_remove_inaccuratedatamodel_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='inaccuraterecommodel',
            name='name',
        ),
        migrations.RemoveField(
            model_name='inaccuraterecommodel',
            name='recommended_name',
        ),
    ]
