# Generated by Django 4.0.3 on 2022-03-17 01:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crm_app', '0010_remove_inaccuraterecommodel_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='brokenlinkmodel',
            name='name',
        ),
    ]
