# Generated by Django 4.0.3 on 2022-03-08 05:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crm_app', '0011_remove_moviemovierecommodel_movie_and_more'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='moviemovierecommodel',
            table='movie_to_movie2',
        ),
    ]
