# Generated by Django 4.0.3 on 2022-03-08 06:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm_app', '0012_alter_moviemovierecommodel_table'),
    ]

    operations = [
        migrations.CreateModel(
            name='TvTvRecomModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tv_id1', models.CharField(default='', max_length=15)),
                ('tv_id2', models.CharField(default='', max_length=15)),
                ('score', models.DecimalField(decimal_places=2, default=0, max_digits=7)),
            ],
            options={
                'db_table': 'tv_to_tv',
            },
        ),
        migrations.AlterField(
            model_name='movietvrecommodel',
            name='movie',
            field=models.CharField(max_length=15),
        ),
        migrations.AlterField(
            model_name='movietvrecommodel',
            name='tv',
            field=models.CharField(max_length=15),
        ),
    ]
