# Generated by Django 4.0.3 on 2022-03-17 02:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm_app', '0013_alter_moviemodel_backdrop_path_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='moviemodel',
            name='tagline',
            field=models.TextField(blank=True, default=''),
        ),
    ]
