# Generated by Django 4.0.3 on 2022-03-08 06:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crm_app', '0013_tvtvrecommodel_alter_movietvrecommodel_movie_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='movietvrecommodel',
            old_name='movie',
            new_name='movie_id',
        ),
        migrations.RenameField(
            model_name='movietvrecommodel',
            old_name='tv',
            new_name='tv_id',
        ),
    ]
