# Generated by Django 4.0.3 on 2022-03-17 02:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm_app', '0015_alter_tvmodel_poster_path_alter_tvmodel_tagline'),
    ]

    operations = [
        migrations.AddField(
            model_name='brokenlinkmodel',
            name='active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='inaccuratedatamodel',
            name='active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='inaccuraterecommodel',
            name='active',
            field=models.BooleanField(default=True),
        ),
    ]
