# Generated by Django 4.0.3 on 2022-03-17 06:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm_app', '0016_brokenlinkmodel_active_inaccuratedatamodel_active_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='moviemovierecommodel',
            name='valid',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='movietvrecommodel',
            name='valid',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='tvtvrecommodel',
            name='valid',
            field=models.BooleanField(default=True),
        ),
    ]
