# Generated by Django 4.0.3 on 2022-03-18 01:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crm_app', '0017_moviemovierecommodel_valid_movietvrecommodel_valid_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='SimilaritysModel',
            new_name='SimilarityModel',
        ),
    ]
