# Generated by Django 4.0.3 on 2022-03-20 07:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm_app', '0018_rename_similaritysmodel_similaritymodel'),
    ]

    operations = [
        migrations.CreateModel(
            name='GlobalVarModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('value', models.CharField(max_length=100)),
            ],
        ),
    ]
