# Generated by Django 4.0.3 on 2022-03-20 08:09

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('crm_app', '0020_missingtitlemodel'),
    ]

    operations = [
        migrations.AddField(
            model_name='missingtitlemodel',
            name='created_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
