# Generated by Django 4.0.3 on 2022-03-22 21:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm_app', '0021_missingtitlemodel_created_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='missingtitlemodel',
            name='active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='missingtitlemodel',
            name='added',
            field=models.CharField(max_length=15, null=True),
        ),
    ]
