# Generated by Django 4.0.3 on 2022-03-22 21:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm_app', '0022_missingtitlemodel_active_missingtitlemodel_added'),
    ]

    operations = [
        migrations.AddField(
            model_name='missingtitlemodel',
            name='completed_date',
            field=models.DateTimeField(null=True),
        ),
    ]
