# Generated by Django 4.0.3 on 2022-03-22 21:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm_app', '0023_missingtitlemodel_completed_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='brokenlinkmodel',
            name='completed_date',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='inaccuratedatamodel',
            name='completed_date',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='inaccuraterecommodel',
            name='completed_date',
            field=models.DateTimeField(null=True),
        ),
    ]
