# Generated by Django 4.0.3 on 2022-03-23 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm_app', '0025_alter_moviemodel_backdrop_path_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='missingtitlemodel',
            name='added',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
    ]
