# Generated by Django 4.0.3 on 2022-03-23 18:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('crm_app', '0026_alter_missingtitlemodel_added'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bookmodel',
            old_name='amazon_link',
            new_name='amazon_redirect_link',
        ),
        migrations.RenameField(
            model_name='bookmodel',
            old_name='isbn_id',
            new_name='isbn',
        ),
        migrations.CreateModel(
            name='MyListModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=10)),
                ('title_type', models.IntegerField(default=0)),
                ('created_date', models.DateField(default=django.utils.timezone.now)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
