# Generated by Django 4.0.3 on 2022-03-23 19:08

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('crm_app', '0028_bookmodel_author_bookmodel_series_bookmodel_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mylistmodel',
            name='created_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
