# Generated by Django 4.0.3 on 2022-03-23 21:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm_app', '0029_alter_mylistmodel_created_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='RecomMovieBookModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('book', models.CharField(blank=True, max_length=15)),
                ('movie', models.CharField(blank=True, max_length=15)),
                ('score', models.IntegerField(default=0)),
            ],
            options={
                'db_table': 'movie_to_book',
            },
        ),
        migrations.CreateModel(
            name='RecomMovieGameModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('game', models.CharField(blank=True, max_length=15)),
                ('movie', models.CharField(blank=True, max_length=15)),
                ('score', models.IntegerField(default=0)),
            ],
            options={
                'db_table': 'movie_to_game',
            },
        ),
    ]
