# Generated by Django 4.0.3 on 2022-03-23 21:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm_app', '0030_recommoviebookmodel_recommoviegamemodel'),
    ]

    operations = [
        migrations.AddField(
            model_name='recommoviebookmodel',
            name='valid',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='recommoviegamemodel',
            name='valid',
            field=models.BooleanField(default=True),
        ),
    ]
