# Generated by Django 4.0.3 on 2022-03-23 21:42

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm_app', '0031_recommoviebookmodel_valid_recommoviegamemodel_valid'),
    ]

    operations = [
        migrations.AddField(
            model_name='gamemodel',
            name='esrb_rating',
            field=models.CharField(default='', max_length=5),
        ),
        migrations.AddField(
            model_name='gamemodel',
            name='genres',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=30), null=True, size=None),
        ),
        migrations.AddField(
            model_name='gamemodel',
            name='keywords',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=30), null=True, size=None),
        ),
        migrations.AddField(
            model_name='gamemodel',
            name='overview',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='gamemodel',
            name='publisher',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=30), null=True, size=None),
        ),
        migrations.AddField(
            model_name='gamemodel',
            name='tags',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=30), null=True, size=None),
        ),
        migrations.AddField(
            model_name='gamemodel',
            name='title',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='gamemodel',
            name='available_at',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=15), null=True, size=None),
        ),
        migrations.AlterField(
            model_name='gamemodel',
            name='background_image',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='gamemodel',
            name='platforms',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=10), null=True, size=None),
        ),
        migrations.AlterField(
            model_name='gamemodel',
            name='release',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='gamemodel',
            name='screenshots',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=100), null=True, size=None),
        ),
        migrations.AlterField(
            model_name='gamemodel',
            name='website',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
