# Generated by Django 4.0.3 on 2022-03-23 21:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crm_app', '0032_gamemodel_esrb_rating_gamemodel_genres_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='recommoviebookmodel',
            old_name='book',
            new_name='book_id',
        ),
        migrations.RenameField(
            model_name='recommoviebookmodel',
            old_name='movie',
            new_name='movie_id',
        ),
    ]
