# Generated by Django 4.0.3 on 2022-03-23 22:10

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm_app', '0033_rename_book_recommoviebookmodel_book_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookmodel',
            name='genres',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(default='', max_length=30), null=True, size=None),
        ),
    ]
